# Generated by Django 5.0.7 on 2025-01-08 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("symbol", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=100)),
                (
                    "current_price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "change",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "change_percent",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                condition=models.Q(("symbol__isnull", False)),
                fields=("user", "symbol"),
                name="unique_user_symbol_case_insensitive",
                violation_error_message="Symbol must be unique for the user, ignoring case.",
            ),
        ),
    ]
