# Generated by Django 5.0.7 on 2025-01-08 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("favorite", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="favorite",
            name="unique_user_symbol_case_insensitive",
        ),
        migrations.RenameField(
            model_name="favorite",
            old_name="symbol",
            new_name="ticker",
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ticker__isnull", False)),
                fields=("user", "ticker"),
                name="unique_user_ticker_case_insensitive",
                violation_error_message="Ticker must be unique for the user, ignoring case.",
            ),
        ),
    ]
