# Generated by Django 5.0.7 on 2025-01-08 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "favorite",
            "0002_remove_favorite_unique_user_symbol_case_insensitive_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="favorite",
            name="change",
        ),
        migrations.RemoveField(
            model_name="favorite",
            name="change_percent",
        ),
        migrations.RemoveField(
            model_name="favorite",
            name="current_price",
        ),
    ]
