# Generated by Django 5.0.7 on 2024-12-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("last_price", models.FloatField(blank=True)),
                ("net_change", models.FloatField(blank=True)),
                ("pct_change", models.FloatField(blank=True)),
                ("marketcap", models.IntegerField(blank=True)),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
                ("ipo_year", models.IntegerField(blank=True)),
                ("volume", models.IntegerField(blank=True)),
                ("sector", models.CharField(blank=True, max_length=100, null=True)),
                ("industry", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
