# Generated by Django 5.1.3 on 2025-01-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_ticker_stock_symbol_remove_stock_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='user',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user',
        ),
        migrations.AlterField(
            model_name='stock',
            name='change',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price change (current - previous)', max_digits=6, null=True),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
