# Generated by Django 5.0.7 on 2025-01-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_portfolio_user_remove_watchlist_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="change_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Price change in percentage",
                max_digits=6,
                null=True,
            ),
        ),
    ]
