# Generated by Django 5.0.7 on 2025-01-08 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_stock_change_percent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stock",
            old_name="symbol",
            new_name="ticker",
        ),
    ]
